// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AV2Rafael.Models;

public partial class Produto
{
    [Key]
    [Column("idProduto")]
    public int IdProduto { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    public int Quantidade { get; set; }

    [Column(TypeName = "money")]
    public decimal Preco { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCriacao { get; set; }

    [Column("idCategoria")]
    public int IdCategoria { get; set; }

    [ForeignKey("IdCategoria")]
    [InverseProperty("Produto")]
    public virtual Categoria IdCategoriaNavigation { get; set; }
    public List<object> ListaProdutos { get; set; }
}